# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hazel_rpc_pb2 as hazel__rpc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hazel_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SceneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSceneInfo = channel.unary_unary(
                '/hazel.rpc.v1.SceneService/GetSceneInfo',
                request_serializer=hazel__rpc__pb2.GetSceneInfoRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.GetSceneInfoResponse.FromString,
                _registered_method=True)
        self.ListEntities = channel.unary_unary(
                '/hazel.rpc.v1.SceneService/ListEntities',
                request_serializer=hazel__rpc__pb2.ListEntitiesRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.ListEntitiesResponse.FromString,
                _registered_method=True)
        self.GetEntity = channel.unary_unary(
                '/hazel.rpc.v1.SceneService/GetEntity',
                request_serializer=hazel__rpc__pb2.GetEntityRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.GetEntityResponse.FromString,
                _registered_method=True)
        self.SetEntityTransform = channel.unary_unary(
                '/hazel.rpc.v1.SceneService/SetEntityTransform',
                request_serializer=hazel__rpc__pb2.SetEntityTransformRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.SetEntityTransformResponse.FromString,
                _registered_method=True)


class SceneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSceneInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEntityTransform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SceneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSceneInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSceneInfo,
                    request_deserializer=hazel__rpc__pb2.GetSceneInfoRequest.FromString,
                    response_serializer=hazel__rpc__pb2.GetSceneInfoResponse.SerializeToString,
            ),
            'ListEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEntities,
                    request_deserializer=hazel__rpc__pb2.ListEntitiesRequest.FromString,
                    response_serializer=hazel__rpc__pb2.ListEntitiesResponse.SerializeToString,
            ),
            'GetEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntity,
                    request_deserializer=hazel__rpc__pb2.GetEntityRequest.FromString,
                    response_serializer=hazel__rpc__pb2.GetEntityResponse.SerializeToString,
            ),
            'SetEntityTransform': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEntityTransform,
                    request_deserializer=hazel__rpc__pb2.SetEntityTransformRequest.FromString,
                    response_serializer=hazel__rpc__pb2.SetEntityTransformResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hazel.rpc.v1.SceneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hazel.rpc.v1.SceneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SceneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSceneInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.SceneService/GetSceneInfo',
            hazel__rpc__pb2.GetSceneInfoRequest.SerializeToString,
            hazel__rpc__pb2.GetSceneInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.SceneService/ListEntities',
            hazel__rpc__pb2.ListEntitiesRequest.SerializeToString,
            hazel__rpc__pb2.ListEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.SceneService/GetEntity',
            hazel__rpc__pb2.GetEntityRequest.SerializeToString,
            hazel__rpc__pb2.GetEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEntityTransform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.SceneService/SetEntityTransform',
            hazel__rpc__pb2.SetEntityTransformRequest.SerializeToString,
            hazel__rpc__pb2.SetEntityTransformResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MujocoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJointState = channel.unary_unary(
                '/hazel.rpc.v1.MujocoService/GetJointState',
                request_serializer=hazel__rpc__pb2.GetJointStateRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.GetJointStateResponse.FromString,
                _registered_method=True)
        self.SendControl = channel.unary_unary(
                '/hazel.rpc.v1.MujocoService/SendControl',
                request_serializer=hazel__rpc__pb2.SendControlRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.SendControlResponse.FromString,
                _registered_method=True)
        self.GetMujocoInfo = channel.unary_unary(
                '/hazel.rpc.v1.MujocoService/GetMujocoInfo',
                request_serializer=hazel__rpc__pb2.GetMujocoInfoRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.GetMujocoInfoResponse.FromString,
                _registered_method=True)
        self.StreamJointState = channel.unary_stream(
                '/hazel.rpc.v1.MujocoService/StreamJointState',
                request_serializer=hazel__rpc__pb2.GetJointStateRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.GetJointStateResponse.FromString,
                _registered_method=True)


class MujocoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJointState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMujocoInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJointState(self, request, context):
        """Streaming variant for continuous state observation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MujocoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJointState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJointState,
                    request_deserializer=hazel__rpc__pb2.GetJointStateRequest.FromString,
                    response_serializer=hazel__rpc__pb2.GetJointStateResponse.SerializeToString,
            ),
            'SendControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControl,
                    request_deserializer=hazel__rpc__pb2.SendControlRequest.FromString,
                    response_serializer=hazel__rpc__pb2.SendControlResponse.SerializeToString,
            ),
            'GetMujocoInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMujocoInfo,
                    request_deserializer=hazel__rpc__pb2.GetMujocoInfoRequest.FromString,
                    response_serializer=hazel__rpc__pb2.GetMujocoInfoResponse.SerializeToString,
            ),
            'StreamJointState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJointState,
                    request_deserializer=hazel__rpc__pb2.GetJointStateRequest.FromString,
                    response_serializer=hazel__rpc__pb2.GetJointStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hazel.rpc.v1.MujocoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hazel.rpc.v1.MujocoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MujocoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJointState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.MujocoService/GetJointState',
            hazel__rpc__pb2.GetJointStateRequest.SerializeToString,
            hazel__rpc__pb2.GetJointStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.MujocoService/SendControl',
            hazel__rpc__pb2.SendControlRequest.SerializeToString,
            hazel__rpc__pb2.SendControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMujocoInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.MujocoService/GetMujocoInfo',
            hazel__rpc__pb2.GetMujocoInfoRequest.SerializeToString,
            hazel__rpc__pb2.GetMujocoInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJointState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hazel.rpc.v1.MujocoService/StreamJointState',
            hazel__rpc__pb2.GetJointStateRequest.SerializeToString,
            hazel__rpc__pb2.GetJointStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TelemetryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTelemetrySchema = channel.unary_unary(
                '/hazel.rpc.v1.TelemetryService/GetTelemetrySchema',
                request_serializer=hazel__rpc__pb2.GetTelemetrySchemaRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.GetTelemetrySchemaResponse.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.unary_stream(
                '/hazel.rpc.v1.TelemetryService/StreamTelemetry',
                request_serializer=hazel__rpc__pb2.StreamTelemetryRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.TelemetryFrame.FromString,
                _registered_method=True)


class TelemetryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTelemetrySchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTelemetrySchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetrySchema,
                    request_deserializer=hazel__rpc__pb2.GetTelemetrySchemaRequest.FromString,
                    response_serializer=hazel__rpc__pb2.GetTelemetrySchemaResponse.SerializeToString,
            ),
            'StreamTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=hazel__rpc__pb2.StreamTelemetryRequest.FromString,
                    response_serializer=hazel__rpc__pb2.TelemetryFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hazel.rpc.v1.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hazel.rpc.v1.TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTelemetrySchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.TelemetryService/GetTelemetrySchema',
            hazel__rpc__pb2.GetTelemetrySchemaRequest.SerializeToString,
            hazel__rpc__pb2.GetTelemetrySchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hazel.rpc.v1.TelemetryService/StreamTelemetry',
            hazel__rpc__pb2.StreamTelemetryRequest.SerializeToString,
            hazel__rpc__pb2.TelemetryFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAgentSchema = channel.unary_unary(
                '/hazel.rpc.v1.AgentService/GetAgentSchema',
                request_serializer=hazel__rpc__pb2.GetAgentSchemaRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.GetAgentSchemaResponse.FromString,
                _registered_method=True)
        self.StreamAgent = channel.unary_stream(
                '/hazel.rpc.v1.AgentService/StreamAgent',
                request_serializer=hazel__rpc__pb2.StreamAgentRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.AgentFrame.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAgentSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAgent(self, request, context):
        """Server-streaming observations (and optional action echo) for a single agent.

        The client specifies which agent to stream via StreamAgentRequest and may
        provide a target FPS hint. Actions are currently sent via MujocoService
        (SendControl); AgentFrame.actions is primarily used for telemetry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAgentSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentSchema,
                    request_deserializer=hazel__rpc__pb2.GetAgentSchemaRequest.FromString,
                    response_serializer=hazel__rpc__pb2.GetAgentSchemaResponse.SerializeToString,
            ),
            'StreamAgent': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAgent,
                    request_deserializer=hazel__rpc__pb2.StreamAgentRequest.FromString,
                    response_serializer=hazel__rpc__pb2.AgentFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hazel.rpc.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hazel.rpc.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAgentSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.AgentService/GetAgentSchema',
            hazel__rpc__pb2.GetAgentSchemaRequest.SerializeToString,
            hazel__rpc__pb2.GetAgentSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hazel.rpc.v1.AgentService/StreamAgent',
            hazel__rpc__pb2.StreamAgentRequest.SerializeToString,
            hazel__rpc__pb2.AgentFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ViewportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetViewportInfo = channel.unary_unary(
                '/hazel.rpc.v1.ViewportService/GetViewportInfo',
                request_serializer=hazel__rpc__pb2.GetViewportInfoRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.GetViewportInfoResponse.FromString,
                _registered_method=True)
        self.StreamViewport = channel.unary_stream(
                '/hazel.rpc.v1.ViewportService/StreamViewport',
                request_serializer=hazel__rpc__pb2.StartViewportStreamRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.ImageFrame.FromString,
                _registered_method=True)


class ViewportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetViewportInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamViewport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViewportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetViewportInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetViewportInfo,
                    request_deserializer=hazel__rpc__pb2.GetViewportInfoRequest.FromString,
                    response_serializer=hazel__rpc__pb2.GetViewportInfoResponse.SerializeToString,
            ),
            'StreamViewport': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamViewport,
                    request_deserializer=hazel__rpc__pb2.StartViewportStreamRequest.FromString,
                    response_serializer=hazel__rpc__pb2.ImageFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hazel.rpc.v1.ViewportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hazel.rpc.v1.ViewportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ViewportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetViewportInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.ViewportService/GetViewportInfo',
            hazel__rpc__pb2.GetViewportInfoRequest.SerializeToString,
            hazel__rpc__pb2.GetViewportInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamViewport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hazel.rpc.v1.ViewportService/StreamViewport',
            hazel__rpc__pb2.StartViewportStreamRequest.SerializeToString,
            hazel__rpc__pb2.ImageFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CameraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCameras = channel.unary_unary(
                '/hazel.rpc.v1.CameraService/ListCameras',
                request_serializer=hazel__rpc__pb2.ListCamerasRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.ListCamerasResponse.FromString,
                _registered_method=True)
        self.StreamCamera = channel.unary_stream(
                '/hazel.rpc.v1.CameraService/StreamCamera',
                request_serializer=hazel__rpc__pb2.StreamCameraRequest.SerializeToString,
                response_deserializer=hazel__rpc__pb2.ImageFrame.FromString,
                _registered_method=True)


class CameraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCameras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCameras,
                    request_deserializer=hazel__rpc__pb2.ListCamerasRequest.FromString,
                    response_serializer=hazel__rpc__pb2.ListCamerasResponse.SerializeToString,
            ),
            'StreamCamera': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCamera,
                    request_deserializer=hazel__rpc__pb2.StreamCameraRequest.FromString,
                    response_serializer=hazel__rpc__pb2.ImageFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hazel.rpc.v1.CameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hazel.rpc.v1.CameraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CameraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hazel.rpc.v1.CameraService/ListCameras',
            hazel__rpc__pb2.ListCamerasRequest.SerializeToString,
            hazel__rpc__pb2.ListCamerasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hazel.rpc.v1.CameraService/StreamCamera',
            hazel__rpc__pb2.StreamCameraRequest.SerializeToString,
            hazel__rpc__pb2.ImageFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
